#!/bin/bash

# This script will ensure Portus' database is ready to be used. It will keep
# waiting for the db to be usable, but the script will exit with an error
# after a certain amount of failed attempts.
#
# The script will automatically import all the SSL certificates from
# `/certificates` into the final system. This is needed to talk with the
# registry API when this one is protected by TLS.
#
# Finally the script will start apache running Portus via mod_rails.

set -e

setup_database() {
  set +e

  TIMEOUT=90
  COUNT=0
  RETRY=1

  export SKIP_MIGRATION=1

  while [ $RETRY -ne 0 ]; do
    case $(SKIP_MIGRATION=1 portusctl exec rails r /check_db.rb | grep DB) in
      "DB_DOWN")
        if [ "$COUNT" -ge "$TIMEOUT" ]; then
          printf " [FAIL]\n"
          echo "Timeout reached, exiting with error"
          exit 1
        fi
        echo "Waiting for mariadb to be ready in 5 seconds"
        sleep 5
        COUNT=$((COUNT+5))
        ;;
      "DB_EMPTY"|"DB_MISSING")
        # create db, apply schema and seed
        echo "Initializing database"
        SKIP_MIGRATION=1 portusctl rake db:setup
        if [ $? -ne 0 ]; then
            echo "Error at setup time"
            exit 1
        fi
        ;;
      "DB_READY")
        echo "Database ready"
        break
        ;;
    esac
  done
  set -e
}

# ensure additional certificates (like the one of the docker registry)
# are known
sudo update-ca-certificates

if [ "$1" == 'portus' ]; then
	setup_database
	exec env sudo /usr/sbin/start_apache2 -DFOREGROUND -k start
fi

if [ "$1" == 'crono' ]; then
	cd /srv/Portus
	RAILS_ENV=production exec bin/crono
fi

exec "$@"

